### PR TITLE
Bump version to v0.1.11

### PR DESCRIPTION
**Pull request by lsetiawan**
## Overview

This PR update the conda package version to `0.1.11` and adds landlab to dependency.

### CODE REVIEW

**Comment by lsetiawan** [comment]
cc. @jphuong

**Comment by lsetiawan** [comment]
@ocefpaf,

Is the error:
`RuntimeError: Setuptools downloading is disabled in conda build. Be sure to add all dependencies in the meta.yaml  url=https://pypi.org/simple/twine/`

caused by https://github.com/Freshwater-Initiative/Observatory/blob/master/setup.py#L49-L51

**Comment by ocefpaf** [comment]
Yep. All those packages should be listed in the `meta.yaml` file.

**Comment by lsetiawan** [comment]
Closing this in favor of #5

**Pull request closed without merging**
